# Generated by Django 3.1.6 on 2021-02-08 16:02

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20210208_1849'),
    ]

    operations = [
        migrations.AddField(
            model_name='postcomment',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 8, 16, 2, 51, 264608, tzinfo=utc), verbose_name='Дата публикации'),
        ),
    ]
